/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Light Mode Tokens (default) ── */
        "inverse-primary": "#c0c1ff",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#2c0051",
        "tertiary-fixed": "#f0dbff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#fffbff",
        secondary: "#00687a",
        "tertiary-fixed-dim": "#ddb7ff",
        "surface-variant": "#d3e4fe",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        primary: "#4648d4",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-container": "#6063ee",
        outline: "#767586",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#6900b3",
        "inverse-on-surface": "#eaf1ff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#006172",
        "tertiary-container": "#9c48ea",
        "on-primary-fixed": "#07006c",
        background: "#f8f9ff",
        "on-error": "#ffffff",
        "surface-dim": "#cbdbf5",
        "outline-variant": "#c7c4d7",
        tertiary: "#8127cf",
        "secondary-fixed": "#acedff",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed-variant": "#004e5c",
        "on-surface-variant": "#464554",
        "on-primary": "#ffffff",
        "surface-tint": "#494bd6",
        "surface-container-highest": "#d3e4fe",
        surface: "#f8f9ff",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "secondary-container": "#57dffe",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "primary-fixed": "#e1e0ff",

        /* ── Dark mode overrides via CSS variables ── */
        /* These are mapped via the dark: prefix in components */
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
